---
# Define supported platforms
dops_gitlab_server_platforms:
  - "CentOS8"
  - "OracleLinux8"

# Group Linux Distributions by family
dops_gitlab_server_os_family: "
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'OracleLinux' ) or
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'RedHat' }}
  {%- elif
      ( ansible_distribution == 'Debian' ) or
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- else -%}
    {{ 'Linux' }}
  {%- endif -%}
  "

# Define default options. Used as a backup for cases where optional Ansible defaults are missing
dops_gitlab_server_firewall_presets:
  zone: "public"

# Multiplatform packages
dops_gitlab_server_profiles_common:
  snap: {}
  flatpak: {}
  pip: {}

# Define common paths
dops_gitlab_server_base_common:
  access:
    user:
      owner: "root"
    group:
      owner: "root"
    mode:
      dir: "0755"
      file: "0644"
      exe: "0755"
  templates: {}
  paths:
    root: "/opt/gitlab"
    etc: "/etc/gitlab"
  files: {}
  run: {}
  etc:
    gitlab_rb: "/etc/gitlab/gitlab.rb"
...
