---
# Define platform specific paths
dops_shellcheck_base:
  paths: "{{ dops_shellcheck_base_common['paths'] }}"
  etc: "{{ dops_shellcheck_base_common['etc'] }}"
  files: "{{ dops_shellcheck_base_common['files'] }}"
  run: "{{ dops_shellcheck_base_common['run'] }}"
  templates: "{{ dops_shellcheck_base_common['templates'] }}"
  access: "{{ dops_shellcheck_base_common['access'] }}"

# Define application package details
dops_shellcheck_profiles:
  snap: "{{ dops_shellcheck_profiles_common['snap'] }}"
  flatpak: "{{ dops_shellcheck_profiles_common['flatpak'] }}"
  distro:
    latest:
      supported: true
      packages:
        - name: "shellcheck"

# Define custom package repositories
dops_shellcheck_repository_custom_yum: []
dops_shellcheck_repository_custom_apt: []

# Set package repositories states
dops_shellcheck_repository_catalog_distro: {}
dops_shellcheck_repository_catalog_yum: {}
dops_shellcheck_repository_catalog_apt: {}
...
