---
- name: "Converge"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Provision"
      vars:
        dops_git_client:
          provision: true
        dops_git_client_repositories:
          - name: "gittest"
            path: "/home/test/git"
            owner: "test"
            email: "test@none.org"
            ignore:
              - ".tmp"
              - ".cache"
      ansible.builtin.include_role:
        name: "dops_git_client"
...
