---
- name: "Converge"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Deploy required packages"
      vars:
        dops_git_client:
          deploy: true
        dops_git_client_application:
          client:
            name: "git"
            type: "distro"
            version: "latest"
            installed: true
          extras:
            name: "extras"
            type: "distro"
            version: "latest"
            installed: true
      ansible.builtin.include_role:
        name: "dops_git_client"
...
