---
- name: "Verify"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Discover packages"
      ansible.builtin.package_facts:
        manager: "auto"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "dops_git_client"

    - name: "Verify required packages are deployed: client"
      ansible.builtin.assert:
        that:
          - item['name'] in ansible_facts['packages']
      loop: "{{
        dops_git_client_profiles['client'][
          dops_git_client_application['client']['type']
        ][
          dops_git_client_application['client']['version']
        ]['packages']
        }}"

    - name: "Verify required packages are deployed: extras"
      ansible.builtin.assert:
        that:
          - item['name'] in ansible_facts['packages']
      loop: "{{
        dops_git_client_profiles['extras'][
          dops_git_client_application['extras']['type']
        ][
          dops_git_client_application['extras']['version']
        ]['packages']
        }}"
...
